name: CI/CD Pipeline

on:
  push:
    branches: [development]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [development, staging, main]

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  development:
    needs: lint
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    uses: ./.github/workflows/deploy-development.yml

  create-staging-pr:
    needs: development
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'development'
    uses: ./.github/workflows/create-pr.yml
    with:
      base: staging
      head: development
      title: "Merge development into staging"
      body: "This PR contains the latest changes from development ready for staging."

  staging:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    uses: ./.github/workflows/deploy-staging.yml

  create-main-pr:
    needs: staging
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    uses: ./.github/workflows/create-pr.yml
    with:
      base: main
      head: staging
      title: "Merge staging into main"
      body: "This PR contains the latest changes from staging ready for main."

  main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deploy-main.yml
