name: CI/CD Pipeline

on:
  push:
    branches: [development, staging]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [development, staging, main]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  development:
    needs: lint
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  staging-promotion:
    needs: development
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: staging
      - name: Reset promotion branch
        run: |
          git fetch origin development:development
          git reset --hard development
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: staging-promotion
          base: development
          title: "Promote development to staging"
          body: "This PR updates staging with the latest changes from development."
          labels: automated-pr

  staging:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'staging'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging

  main-promotion:
    needs: staging
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin staging:staging
          git reset --hard staging
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main-promotion
          base: staging
          title: "Promote staging to main"
          body: "This PR updates main with the latest changes from staging."
          labels: automated-pr

  main:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
