name: CI/CD Pipeline

on:
  push:
    branches: [development, staging, main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [development, staging, main]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  development:
    needs: lint
    if: github.ref == 'refs/heads/development'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development

  create-staging-pr:
    needs: development
    if: github.ref == 'refs/heads/development' && github.event_name == 'push'
    uses: ./.github/workflows/create-pr.yml
    with:
      base: "staging"
      head: "development"
      title: "Promote development to staging"
      body: "This PR updates staging with the latest changes from development."

  staging:
    if: github.ref == 'refs/heads/staging'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: staging

  create-main-pr:
    needs: staging
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    uses: ./.github/workflows/create-pr.yml
    with:
      base: "main"
      head: "staging"
      title: "Promote staging to main"
      body: "This PR updates main with the latest changes from staging."

  main:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: main
